#+title: \Huge{Método das séries (Frobenius)}
#+options: toc:1 date:nil 
#+language: pt
#+setupfile: ~/Dropbox/Templates/mathematics.org
#+latex: \newpage

* Mini revisão de séries e séries de Taylor
** Multiplicação de duas séries: 
  Dadas as funões analiticas em \( x_0 \) , $f(x)$ e $g(x)$, com
  \[ f(x) = \sum_{n = 0}^{\infty} a_n (x - x_0)^n \text{ e } g(x) = \sum_{n = 0}^{\infty}b_n (x - x_0)^n \] 
  vale a seguinte relação
  \[ f(x) g(x) := \bigg[\sum_{n = 0}^{\infty} a_n (x - x_0)^n  \bigg] \bigg[\sum_{n = 0}^{\infty} b_n (x - x_0)^n  \bigg] \]

  \[ f(x) g(x) := \sum_{n = 0}^{\infty} c_n (x-x_0)^n \]
  onde \( c_n = a_0 b_n + a_1 b_{n-1} + \dots + a_n b_0 \) .
** Série de taylor em torno de um ponto \( x_0 \):

\[ \boxed{ f(x) =  \sum_{n = 0}^{\infty} \frac{f^{(n)}(x_0)}{n!} (x-x_0)^n } \]

* Solução em torno de pontos regulares 
** Introdução e analiticidade de séries de potências
Dada a série de potências $ \sum a_n (x-x_0)^n$, se a série
converge para valores de \( x \) num intervalo \( x_0 - \delta, x_0 + \delta \) , \( \delta > 0 \) ,
então a série é analitica em \( x = x_0 \) .
- *Exemplo*: Dada a EDO \( a(x) y''(x) b(x)y'(x) + c(x)y(x) = 0 \) 
  \[ y''(x) + p(x) y'(x) + q(x) y(x) = 0  \]

  * 1º: Escolher o ponto \( x_0 \) que vamos analisar.
  * 2º: Estudar a analiticidade da série.

- *Exemplo*: \( (1 - x) y'' + y = 0  \) 

  \[ y'' + \frac{1}{1 - x}y = 0, p(x) = \frac{1}{1 - x} = \sum_{n = 0}^{\infty} x^n \]

  Pelo critério da razão: \( \lim_{n \infty} |r_n| = |x| \) , convergente no intervalo \( (-1, 1) \)
  e convergente no ponto \( 0 \) . Escrevendo a EDO em formato de séries:

  \[ \sum_{n = 0}^{\infty} (n + 2)(n+ 1) a_{n+2} x^n + \bigg[ \sum_{n = 0}^{\infty} x^n \bigg]
  \bigg[ \sum_{n = 0}^{\infty} a_n x^n \bigg] = 0\]

** Solução em séries em torno de pontos regulares

*** *Exemplo*: \( y''(x) + \sin(x) y(x) = 0 \) 

    Temos \( p(x) = 0 \) e \( q(x) = \sin(x) = \sum_{n = 0}^{\infty} (-1)^n \frac{x^{(2n +
    1)}}{(2n + 1)!} \) , ambas funções são analiticas em torno de \( x_0
    \). Escolhendo
    \( x_0 = 0 \) temos:

    \[ \sum_{n = 0}^{\infty} (n + 2)(n+1) a_{n + 2} x^n + \left[ \sum_{n = 0}^{\infty} (-1)^n
    \frac{x^{(2n + 1)}}{(2n + 1)!} \right] \left[ \sum_{n = 0}^{\infty} a_n x^n \right] = 0\]

    Nesse tipo de resolução podemos definir uma ordem n e tentar encontrar o termo geral \( a_n \) e
    então retornar à série original de \( y(x) \) nas condições iniciais dadas.
    

    Abrindo os somatórios e agrupando os termos a partir das menores potências de \( x \) até \( x^3 \)  ;

    \[ (2 \cdot 1 a_2 + 3 \cdot 2 a_3 x + 4 \cdot 3 a_4 x^2 + 5 \cdot  4 x^3 + \cdots) +
    \left[ x - \frac{x^3}{3!} + \frac{x^5}{5!} - \cdots  \right] \left[ a_0 + a_1 x + a_2 x^2 + a_3
    x^3 + \cdots  \right]\]
    \[ 2 a_2 + (6 a_3 + a_0) x + (12 a_4 + a_1) x^2 + (20 a_5 + a_2 - \frac{a_0}{6})x^3 +
    \mathcal{O}(x^4) = 0 \]

    Relação de independência linear, ou seja, os coeficientes *devem* ser nulos.

    \[ \begin{cases}
    a_2 = 0 \\
    6a_3 + a_0 = 0 \\
    12 a_4 + a_1 = 0 \\
    \vdots 
    \end{cases}  \Rightarrow  \begin{align} a_3 = - \frac{a_0}{3} \\ a_4 = - \frac{a_1}{12} \\ a_5
    =  - \frac{a_0}{120}\end{align}\]
  
    Escrevendo \( y(x) \) em termo dos coeficientes encontrados: 

    \[ y(x) =  a_0 + a_1 x  - \frac{a_0}{6}x^3 - \frac{a_1}{12}x^4 + \frac{a_0}{120} x^5 + \cdots \]
    \[ y(x) = a_0 \left[ 1 - \frac{x^3}{3!} + \frac{x^5}{5!} + \cdots  \right] + a_1 \left[ x -
    \frac{x^4}{12} + \cdots  \right]\]

    Onde \( a_0 \) e \( a_1 \) são as condições de contorno.

    


  



  
*** *Exemplo*: \( y'' + k^2 y = 0, k \in \mathbb{R} \text{ e } y (x) = ?  \)
    Exemplo de uma EDO que podemos resolver sem o método de séries. Caso do movimento oscilatório.


    De forma direta, temos

    \[ \sum_{n = 0}^{\infty} \left[ (n+2) (n+1) a_{n + 2} x^n \right]  + k^2 \sum_{n = 0}^{\infty} a_n x^n = 0\]
    \[ \sum_{n = 0}^{\infty} \left[ (n+2)(n + 1) a_{n + 2} + k^2 a_n \right] x^n = 0  \]
    \[ a_{n + 2} = - k^2 \frac{a_n}{(n + 2)(n + 1)}, n = 0, 1, 2, ... \]

     $$ \begin{flalign*}
    a_2 & = - k^2 \frac{a_0}{2} &\\
    a_3 & = -k^2 \frac{a_1}{3 \cdot  2} &\\
    a_4 & = -k^2 \frac{a_2}{4 \cdot 3 } = k^4 \frac{a_0}{4 \cdot  3 \cdot  2 \cdot  1 }&\\
    a_5 & = -k^2 \frac{a_3}{5 \cdot 4 } = k^4 \frac{a_1}{5 \cdot  4 \cdot  3 \cdot  2 }
    \end{flalign*} $$

    Separando em termos pares e ímpares:

    - n par: \( n = 2j, j = 0, 1, 2, ... \)
      \[ a_{2j + 2} = - k^2 \frac{a_{2j}}{(2j + 2)(2j + 1)} = - \frac{k^2}{(2j+2)(2j+1)} \left[ -
      \frac{k^2 a_{2j - 2}}{(2j)(2j -1)} \right]  \]
      \[ a_{2j + 2} = \frac{(-k^2)(-k^2)\cdot  \cdots (-k^2) a_0}{(2j+2)(2j + 1)(2j)(2j - 1) \cdots
      2)} = \frac{(-k^2)^{j + 1} a_0}{(2j + 2)!}\]
      \[ a_{2j + 2} = \frac{(-k^2)^{j + 1} a_0}{[2(j + 1)]!} \Rightarrow \boxed{ a_{2j} = (-1)^j\frac{
      k^{2j} a_0}{(2j)!}} \]
      
    - n ímpar: \( n = 2j + 1 \) 

      \[ a_{2j + 3} = - \frac{k^2 a_{2j + 1}}{(2j + 3)(2j + 2)} = \frac{(-k^2)(-k^2) a_{2j-1}}{(2j+3)(2j+2)(2j+1)(2j)\cdots } \]
      \[ a_{2j + 3} =  \frac{(-k^2)(-k^2) \cdots (-k^2) a_1}{(2j+3)(2j+2)(2j+1)\cdots  3 \cdot  2} \]
      \[ a_{2j+3} = \frac{(-1)^j (k^2)^{j + 1} a_1}{(2j + 3)!} \Rightarrow \boxed{ a_{2j + 1} =
      (-1)^{j} \frac{(k)^{2j} a_1}{(2j + 1)!}} \]

    Voltando à série original, temos
    \[ y(x) = \sum_{n = 0}^{\infty} a_n x^n = \sum_{\text{n par}} a_n x^n + \sum_{\text{n impar}}
    a_n x^n \]
    
    \[ y(x) = a_0 \sum_{n = 0}^{\infty} (-1)^n \frac{k^{2n} x^{2n}}{(2n)!} + \underbrace{a_1 \sum_{n =
    0}^{\infty}(-1)^n \frac{k^{2n} x^{2n + 1}}{(2n + 1)!}}_{= \frac{a_1}{k} \left[ kx - \frac{k^3
    x^3}{3!} + \frac{k^5 x^5}{5!} - \frac{k^7 x^7}{7!} + \cdots  \right]} \]

    \[ y(x) = a_0 \cos(kx)  + \frac{a_1}{k} \sin(kx) \]

    \[ \boxed{ y(x) = A \cos(kx) + B \sin (kx) } \]
    
* Método de séries para pontos singulares regulares







